apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: backend-media
  name: backend-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
