apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Administrator\scoop\apps\kompose\current\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: backend
