# Generated by Django 5.2 on 2025-05-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_notification_id_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securitypolicy',
            name='policy_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
