# Generated by Django 5.2 on 2025-05-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='protraint',
            field=models.ImageField(blank=True, null=True, upload_to='protraint/'),
        ),
    ]
