# Generated by Django 5.2 on 2025-05-27 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_captcha_is_used_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='receiver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user.user'),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='sender',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '已封禁')], default=0),
        ),
    ]
