# Generated by Django 5.2 on 2025-05-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_securitypolicy_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
