# Generated by Django 5.2 on 2025-05-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
