apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30180
  type: NodePort
  selector:
    io.kompose.service: backend
