apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - image: backend:latest
          imagePullPolicy: Never
          name: cfmp-backend
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
