# Generated by Django 5.2.1 on 2025-05-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_avatar'),
        ('user', '0008_captcha'),
    ]

    operations = [
    ]
