# Generated by Django 5.2.1 on 2025-05-24 04:59

import minio_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_merge_0008_alter_user_avatar_0008_captcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=minio_storage.storage.MinioMediaStorage(), upload_to=''),
        ),
    ]
