# Generated by Django 5.2 on 2025-05-14 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collecter_id',
            new_name='collecter',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='collection_id',
            new_name='collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
