# Generated by Django 5.2 on 2025-05-21 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_collecter_id_collection_collecter_and_more'),
        ('user', '0004_remove_user_phone_user_captcha_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
