# Generated by Django 5.2 on 2025-05-22 07:35

import django.db.models.deletion
import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('media_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('media', models.ImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(), upload_to='product_media/')),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='product.product')),
            ],
            options={
                'db_table': 'product_media',
                'ordering': ['-is_main', 'created_at'],
            },
        ),
    ]
