# Generated by Django 5.2 on 2025-05-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_rename_user_column"),
        ("user", "0005_user_is_active_user_is_authenticated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
        ),
    ]
