# Generated by Django 5.2 on 2025-05-22 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_rename_user_product_user_id"),
        ("user", "0005_user_is_active_user_is_authenticated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="user_id",
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
        ),
    ]
