# Generated by Django 5.2 on 2025-05-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_rating_avg_product_visit_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
    ]
