# Generated by Django 5.2 on 2025-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_productreview_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '上架'), (1, '封禁'), (2, '已出售')], default=0),
        ),
    ]
