# Generated by Django 5.2 on 2025-05-22 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_remove_product_product_img_productmedia"),
        ("user", "0005_user_is_active_user_is_authenticated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.SmallIntegerField(choices=[(0, "上架"), (1, "下架")], default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
        ),
    ]
