# Generated by Django 5.2 on 2025-05-22 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_product_status_alter_product_user"),
    ]

    operations = []
