# Generated by Django 5.2 on 2025-05-22 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_alter_product_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user",
            new_name="user_id",
        ),
    ]
