# Generated by Django 5.2.1 on 2025-05-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_user'),
        ('product', '0011_remove_product_user_id_product_user'),
    ]

    operations = [
    ]
