# Generated by Django 5.2 on 2025-05-23 02:00

import minio_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_merge_20250523_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='media',
            field=models.ImageField(blank=True, null=True, storage=minio_storage.storage.MinioMediaStorage(), upload_to='product_media/'),
        ),
    ]
