# Generated by Django 5.2.1 on 2025-05-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_merge_20250523_2142'),
        ('product', '0012_merge_20250524_1134'),
    ]

    operations = [
    ]
