# Generated by Django 5.2 on 2025-05-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_merge_20250523_2142'),
        ('product', '0013_alter_productmedia_media'),
    ]

    operations = [
    ]
