# Generated by Django 5.2 on 2025-05-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_merge_20250524_1258'),
        ('product', '0014_merge_20250524_1609'),
    ]

    operations = [
    ]
