# Generated by Django 5.2 on 2025-05-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_merge_20250525_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='function',
            field=models.SmallIntegerField(choices=[(0, '包邮'), (1, '自提')], default=0),
        ),
    ]
