# Generated by Django 5.2 on 2025-05-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_avg',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='平均评分', max_digits=2),
        ),
        migrations.AddField(
            model_name='product',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
