# Generated by Django 5.2 on 2025-05-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '上架'), (1, '封禁'), (2, '已出售'), (3, '未审核')], default=0),
        ),
    ]
