# Generated by Django 5.2 on 2025-05-14 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('event', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_type', models.SmallIntegerField()),
                ('target_id', models.IntegerField()),
                ('action', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ban_time', models.IntegerField(default=0)),
                ('ban_type', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'violation',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_type', models.SmallIntegerField()),
                ('target_id', models.IntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('complainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='ComplaintReview',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_id', models.IntegerField(default=0)),
                ('target_type', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=100)),
                ('reviewer_id', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'complaint_review',
            },
        ),
    ]
