# Generated by Django 5.2 on 2025-05-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complainer_id',
            new_name='complainer',
        ),
        migrations.RenameField(
            model_name='complaintreview',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
    ]
