# Generated by Django 5.2 on 2025-05-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_remove_complaint_result_remove_complaint_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complaintreview',
            table='complaint_review',
        ),
    ]
