# Generated by Django 5.2 on 2025-05-14 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_alter_complaintreview_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complainer',
            field=models.ForeignKey(db_column='complainer_id', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='complainer',
            new_name='complainer_id',
        ),
        migrations.AlterField(
            model_name='complaintreview',
            name='reviewer',
            field=models.ForeignKey(db_column='reviewer_id', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.RenameField(
            model_name='complaintreview',
            old_name='reviewer',
            new_name='reviewer_id',
        ),
    ]
