# Generated by Django 5.2 on 2025-05-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_rename_complainer_id_complaint_complainer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complainer',
            new_name='complainer_id',
        ),
    ]
