# Generated by Django 5.2 on 2025-05-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_rename_complainer_complaint_complainer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintreview',
            old_name='complaint',
            new_name='complaint_id',
        ),
        migrations.RenameField(
            model_name='complaintreview',
            old_name='reviewer',
            new_name='reviewer_id',
        ),
    ]
