# Generated by Django 5.2 on 2025-05-12 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_category_category_id_alter_chatlog_chat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='model.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.user')),
            ],
            options={
                'db_table': 'product_review',
                'unique_together': {('product', 'user')},
            },
        ),
    ]
