name: CFMP_deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Aliyun
        run: |
          sshpass -p ${{secrets.ECS_PASSWORD}} ssh -o StrictHostKeyChecking=no root@${{secrets.ECS_IP}} "
            if [ ! -d ~/CFMP ]; then
              git clone https://github.com/LittttleRed/CFMP.git ~/CFMP
            fi &&
            cd ~/CFMP &&
            git pull origin master &&
            docker-compose down || true &&
            docker-compose build &&
            docker-compose up -d
          "
